language: c
sudo: enabled
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: linux
      dist: precise
      sudo: required
before_install:
  - sudo make build_before
script:
  - sudo make pkg-build
  - sudo make pkg-test
sudo: required
