language: c
sudo: enabled
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: linux
      dist: precise
      sudo: required
script:
  - set
  - make ci-build
sudo: required
