version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install make
          command: apt-get update -qq && apt-get install -y make
      - run:
          name: Build before
          command: make build_before
      - run:
          name: Build package
          command: make pkg-build
      - run:
          name: Running tests
          command: make pkg-test
