version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    environment:
      CIRCLE_REPOSITORY_URL: https://github.com/LavaVPS/libsysemul.git
    steps:
      - run:
          name: Install git and make
          command: apt-get update -qq && apt-get install -y git make
      - run:
          name: Checkout
          command: |
	    git clone "$CIRCLE_REPOSITORY_URL" .
	    git reset --hard "$CIRCLE_SHA1"
      - run:
          name: Build before
          command: make build_before
      - run:
          name: Build package
          command: make pkg-build
      - run:
          name: Running tests
          command: make pkg-test
